<?php
   
?>

<h1>Lista de pessoas</h1>

<a href="<?=$this->url('person',['action'=>'add'])?>" class="btn btn-success">Adicionar nova pessoa</a>

<table class="table table-stripped">
    <tr>
        <th>Código</th>
        <th>Nome</th>
    <tr>
<?php
    foreach($persons as $pes) {
?>
    <tr>
        <td><?=$pes->getId()?></td>
        <td><?=$pes->getName()?></td>
        <td>
            <a href="<?=$this->url('person',['action'=>'edit','id'=>$pes->getId()])?>" class="btn btn-info"><i class="glyphicon glyphicon-edit"></i></a>
            <a href="<?=$this->url('person',['action'=>'remove','id'=>$pes->getId()])?>" class="btn btn-danger"><i class="glyphicon glyphicon-trash"></i></a>
        </td>
    </tr>
<?php
    }
?>
</table>