<?php
   
?>

<h1>Lista de pessoas</h1>

<a href="<?=$this->url('person',['action'=>'add'])?>" class="btn btn-success">Adicionar nova pessoa</a>

<table class="table table-stripped">
    <tr>
        <th>Código</th>
        <th>Nome</th>
    <tr>
<?php
    foreach($persons as $pes) {
?>
    <tr>
        <td><?=$pes->getId()?></td>
        <td><?=$pes->getName()?></td>
    </tr>
<?php
    }
?>
</table>